# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70438820292160f7db946c3d3dcdb443c65a19f169049c3486e9023ecd2bd798d8158b56e3ee5ad9ddee689600cdc184e2fc29db917270bcb38a9116484c1a10

test:
  secret_key_base: ccdde9b71e9672b245e04dff3dd48c9822ba3723febacca83ad3c449a6feda19394f2abfaecca3fbb4480aa728803644e850e2c5e7c29ec21d1eb2369fcbcdc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
